@startuml
'https://plantuml.com/activity-diagram-beta
|User|
start
:Membuka app;
|App|
:Menampilkan Halaman Home;
|User|
:Memilih navbar menu;
|App|
:Menampilkan daftar menu;
|User|
:Memilih menu Pengembang;
|App|
:Menampilkan daftar Pengembang;
|User|
stop
@enduml
