@startuml
'https://plantuml.com/activity-diagram-beta
|User|
start
:Membuka app;
|App|
:Menampilkan Halaman Home;
|User|
:Membuka halaman agen;
|App|
:Menampilkan halaman agen;
|User|
:Memilih agen;
|App|
:Menampilkan halaman detail agen;
|User|
stop
@enduml
