@startuml
'https://plantuml.com/activity-diagram-beta
|User|
start
:Membuka app;
|App|
:Menampilkan Halaman Home;
|User|
:Membuka halaman properti;
|App|
:Menampilkan halaman properti;
|User|
:Memilih properti;
|App|
:Menampilkan halaman detail properti;
|User|
stop
@enduml
